services:
  db:
    image: postgres:16
    container_name: movies_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - movies-network

  api:
    build: .
    container_name: movies_api
    command: npm run dev          
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app                    
    working_dir: /app
    networks:
      - movies-network

networks:
  movies-network:
